import type { CredentialRecipe, StarterKit } from './types.js';

const manualValidation = (description: string) => ({ kind: 'manual' as const, description });
const n8nValidation = (description: string) => ({ kind: 'n8n-credential-test' as const, description });

export const CREDENTIAL_RECIPES: CredentialRecipe[] = [
  {
    id: 'openai-native',
    service: 'llm',
    label: 'OpenAI',
    credentialTypeName: 'openAiApi',
    authMethod: 'api-key',
    requiredInputs: [
      { key: 'apiKey', label: 'OpenAI API key', required: true, secret: true },
      { key: 'url', label: 'Base URL', required: false },
    ],
    supportedNodes: ['OpenAI Chat Model', 'OpenAI', 'OpenAI Assistant', 'Embeddings OpenAI'],
    validation: n8nValidation('Run the native n8n OpenAI credential test.'),
    setupFlow: { kind: 'manual', steps: ['Provide an OpenAI API key.', 'Optionally provide a custom OpenAI-compatible base URL.', 'Create or update the native n8n credential.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
  {
    id: 'anthropic-native',
    service: 'llm',
    label: 'Anthropic',
    credentialTypeName: 'anthropicApi',
    authMethod: 'api-key',
    requiredInputs: [
      { key: 'apiKey', label: 'Anthropic API key', required: true, secret: true },
      { key: 'url', label: 'Base URL', required: false },
    ],
    supportedNodes: ['Anthropic Chat Model', 'Anthropic'],
    validation: n8nValidation('Run the native n8n Anthropic credential test.'),
    setupFlow: { kind: 'manual', steps: ['Provide an Anthropic API key.', 'Optionally provide a custom Anthropic base URL.', 'Create or update the native n8n credential.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
  {
    id: 'google-gemini-native',
    service: 'llm',
    label: 'Google Gemini',
    credentialTypeName: 'googlePalmApi',
    authMethod: 'api-key',
    requiredInputs: [{ key: 'apiKey', label: 'Google AI API key', required: true, secret: true }],
    supportedNodes: ['Google Gemini Chat Model', 'Google Gemini', 'Embeddings Google Gemini'],
    validation: n8nValidation('Run the native n8n Google Gemini credential test.'),
    setupFlow: { kind: 'manual', steps: ['Provide a Google AI API key.', 'Create or update the native n8n credential.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
  {
    id: 'llm-proxy',
    service: 'llm',
    label: 'LLM Proxy',
    credentialTypeName: 'openAiApi',
    authMethod: 'llm-proxy',
    requiredInputs: [],
    supportedNodes: ['OpenAI Chat Model', 'OpenAI', 'AI Agent', 'LM Chat OpenAI'],
    validation: { kind: 'llm-proxy-health', description: 'Probe the proxy health endpoint and run an n8n credential test when available.' },
    setupFlow: { kind: 'automatic', steps: ['Resolve an LLM source.', 'Create an OpenAI-compatible n8n credential pointing to the proxy.', 'Test the credential.'] },
    frictionLevel: 'low',
    riskLevel: 'low',
  },
  {
    id: 'http-header',
    service: 'http',
    label: 'HTTP Header Auth',
    credentialTypeName: 'httpHeaderAuth',
    authMethod: 'header',
    requiredInputs: [
      { key: 'name', label: 'Header name', required: true },
      { key: 'value', label: 'Header value', required: true, secret: true },
    ],
    supportedNodes: ['HTTP Request'],
    validation: manualValidation('HTTP credentials are validated against a user-provided API endpoint.'),
    setupFlow: { kind: 'manual', steps: ['Provide the header name.', 'Provide the header value or token.', 'Optionally test against a known endpoint.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
  {
    id: 'http-bearer',
    service: 'http',
    label: 'HTTP Bearer Token',
    credentialTypeName: 'httpBearerAuth',
    authMethod: 'bearer',
    requiredInputs: [{ key: 'token', label: 'Bearer token', required: true, secret: true }],
    supportedNodes: ['HTTP Request'],
    validation: manualValidation('Bearer credentials are validated against a user-provided API endpoint.'),
    setupFlow: { kind: 'manual', steps: ['Provide a bearer token.', 'Optionally test against a known endpoint.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
  {
    id: 'webhook-shared-secret',
    service: 'webhook',
    label: 'Webhook Shared Secret',
    credentialTypeName: 'httpHeaderAuth',
    authMethod: 'webhook-secret',
    requiredInputs: [{ key: 'secret', label: 'Shared secret', required: true, secret: true }],
    supportedNodes: ['Webhook'],
    validation: manualValidation('Webhook shared secrets are validated by invoking a generated webhook.'),
    setupFlow: { kind: 'automatic', steps: ['Generate or accept a shared secret.', 'Expose it to workflow generation as a required header.'] },
    frictionLevel: 'low',
    riskLevel: 'low',
  },
  {
    id: 'google-oauth',
    service: 'google',
    label: 'Google OAuth Bundle',
    credentialTypeName: 'googleOAuth2Api',
    authMethod: 'oauth2',
    requiredInputs: [
      { key: 'clientId', label: 'OAuth client ID', required: true },
      { key: 'clientSecret', label: 'OAuth client secret', required: true, secret: true },
    ],
    supportedNodes: ['Google Drive', 'Google Sheets', 'Gmail', 'Google Calendar', 'Google Docs'],
    validation: n8nValidation('Run the native n8n OAuth credential test.'),
    setupFlow: { kind: 'guided', steps: ['Create a Google Cloud project.', 'Enable the Drive, Sheets, Gmail, Calendar, and Docs APIs.', 'Configure consent screen and redirect URL.', 'Authorize in n8n.'] },
    frictionLevel: 'high',
    riskLevel: 'medium',
  },
  {
    id: 'notion-token',
    service: 'notion',
    label: 'Notion Internal Integration',
    credentialTypeName: 'notionApi',
    authMethod: 'api-key',
    requiredInputs: [{ key: 'token', label: 'Internal integration token', required: true, secret: true }],
    supportedNodes: ['Notion'],
    validation: n8nValidation('Run the Notion credential test and remind the user to share pages with the integration.'),
    setupFlow: { kind: 'guided', steps: ['Create a Notion internal integration.', 'Paste the integration token.', 'Share target pages or databases with the integration.'] },
    frictionLevel: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'slack-oauth',
    service: 'slack',
    label: 'Slack OAuth',
    credentialTypeName: 'slackOAuth2Api',
    authMethod: 'oauth2',
    requiredInputs: [
      { key: 'clientId', label: 'Slack client ID', required: true },
      { key: 'clientSecret', label: 'Slack client secret', required: true, secret: true },
    ],
    supportedNodes: ['Slack', 'Slack Trigger'],
    validation: n8nValidation('Run the native n8n Slack credential test.'),
    setupFlow: { kind: 'guided', steps: ['Create or choose a Slack app.', 'Configure redirect URL and scopes.', 'Authorize the workspace in n8n.'] },
    frictionLevel: 'high',
    riskLevel: 'medium',
  },
  {
    id: 'supabase-api-key',
    service: 'supabase',
    label: 'Supabase API Key',
    credentialTypeName: 'supabaseApi',
    authMethod: 'api-key',
    requiredInputs: [
      { key: 'projectUrl', label: 'Project URL', required: true },
      { key: 'apiKey', label: 'API key', required: true, secret: true },
    ],
    supportedNodes: ['Supabase', 'HTTP Request', 'Postgres'],
    validation: n8nValidation('Run the Supabase credential test when the node supports it.'),
    setupFlow: { kind: 'manual', steps: ['Provide project URL.', 'Provide anon or service role key according to the workflow risk.'] },
    frictionLevel: 'medium',
    riskLevel: 'high',
  },
  {
    id: 'airtable-pat',
    service: 'airtable',
    label: 'Airtable Personal Access Token',
    credentialTypeName: 'airtableTokenApi',
    authMethod: 'pat',
    requiredInputs: [{ key: 'token', label: 'Personal access token', required: true, secret: true }],
    supportedNodes: ['Airtable'],
    validation: n8nValidation('Run the Airtable credential test.'),
    setupFlow: { kind: 'manual', steps: ['Create an Airtable PAT with the required bases and scopes.', 'Paste the token.'] },
    frictionLevel: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'github-pat',
    service: 'github',
    label: 'GitHub Personal Access Token',
    credentialTypeName: 'githubApi',
    authMethod: 'pat',
    requiredInputs: [{ key: 'token', label: 'Personal access token', required: true, secret: true }],
    supportedNodes: ['GitHub'],
    validation: n8nValidation('Run the GitHub credential test.'),
    setupFlow: { kind: 'manual', steps: ['Create a fine-grained GitHub token.', 'Grant only the repositories and scopes required by workflows.', 'Paste the token.'] },
    frictionLevel: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'hubspot-token',
    service: 'hubspot',
    label: 'HubSpot App Token',
    credentialTypeName: 'hubspotApi',
    authMethod: 'api-key',
    requiredInputs: [{ key: 'token', label: 'App token', required: true, secret: true }],
    supportedNodes: ['HubSpot'],
    validation: n8nValidation('Run the HubSpot credential test.'),
    setupFlow: { kind: 'manual', steps: ['Create a private app in HubSpot.', 'Grant required CRM scopes.', 'Paste the token.'] },
    frictionLevel: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'microsoft-oauth',
    service: 'microsoft',
    label: 'Microsoft 365 OAuth',
    credentialTypeName: 'microsoftOAuth2Api',
    authMethod: 'oauth2',
    requiredInputs: [
      { key: 'clientId', label: 'Azure app client ID', required: true },
      { key: 'clientSecret', label: 'Azure app client secret', required: true, secret: true },
      { key: 'tenantId', label: 'Tenant ID', required: false },
    ],
    supportedNodes: ['Microsoft Outlook', 'Microsoft OneDrive', 'Microsoft Excel', 'Microsoft Teams'],
    validation: n8nValidation('Run the native Microsoft OAuth credential test.'),
    setupFlow: { kind: 'guided', steps: ['Register an Azure app.', 'Configure redirect URL and scopes.', 'Collect admin consent if required.', 'Authorize in n8n.'] },
    frictionLevel: 'high',
    riskLevel: 'medium',
  },
  {
    id: 'postgres',
    service: 'postgres',
    label: 'Postgres',
    credentialTypeName: 'postgres',
    authMethod: 'database',
    requiredInputs: [
      { key: 'host', label: 'Host', required: true },
      { key: 'port', label: 'Port', required: true },
      { key: 'database', label: 'Database', required: true },
      { key: 'user', label: 'User', required: true },
      { key: 'password', label: 'Password', required: true, secret: true },
      { key: 'ssl', label: 'SSL mode', required: false },
    ],
    supportedNodes: ['Postgres', 'PGVector Store'],
    validation: n8nValidation('Run the Postgres credential test.'),
    setupFlow: { kind: 'manual', steps: ['Provide connection fields.', 'Choose SSL mode.', 'Optionally configure SSH tunneling later.'] },
    frictionLevel: 'medium',
    riskLevel: 'high',
  },
  {
    id: 'smtp',
    service: 'email',
    label: 'SMTP',
    credentialTypeName: 'smtp',
    authMethod: 'basic',
    requiredInputs: [
      { key: 'host', label: 'Host', required: true },
      { key: 'port', label: 'Port', required: true },
      { key: 'user', label: 'User', required: true },
      { key: 'password', label: 'Password', required: true, secret: true },
    ],
    supportedNodes: ['Send Email'],
    validation: n8nValidation('Run the SMTP credential test.'),
    setupFlow: { kind: 'manual', steps: ['Provide SMTP server details.', 'Prefer OAuth2 for Microsoft or Google accounts when available.'] },
    frictionLevel: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'telegram-bot',
    service: 'telegram',
    label: 'Telegram Bot',
    credentialTypeName: 'telegramApi',
    authMethod: 'api-key',
    requiredInputs: [{ key: 'botToken', label: 'Bot token', required: true, secret: true }],
    supportedNodes: ['Telegram', 'Telegram Trigger'],
    validation: n8nValidation('Run the Telegram credential test.'),
    setupFlow: { kind: 'manual', steps: ['Create a bot with BotFather.', 'Paste the bot token.'] },
    frictionLevel: 'low',
    riskLevel: 'medium',
  },
];

export const STARTER_KITS: StarterKit[] = [
  { id: 'ai-workflows', label: 'AI workflows', recipeIds: ['openai-native', 'anthropic-native', 'google-gemini-native', 'http-header', 'webhook-shared-secret'] },
  { id: 'productivity', label: 'Productivity', recipeIds: ['google-oauth', 'notion-token', 'slack-oauth'] },
  { id: 'data', label: 'Data', recipeIds: ['supabase-api-key', 'airtable-pat', 'postgres'] },
  { id: 'dev', label: 'Dev', recipeIds: ['github-pat', 'http-header', 'http-bearer'] },
  { id: 'communication', label: 'Communication', recipeIds: ['slack-oauth', 'telegram-bot', 'smtp', 'microsoft-oauth'] },
];

export function listCredentialRecipes(): CredentialRecipe[] {
  return CREDENTIAL_RECIPES.map((recipe) => ({ ...recipe, requiredInputs: [...recipe.requiredInputs], supportedNodes: [...recipe.supportedNodes] }));
}

export function getCredentialRecipe(recipeId: string): CredentialRecipe | undefined {
  return listCredentialRecipes().find((recipe) => recipe.id === recipeId);
}

export function listStarterKits(): StarterKit[] {
  return STARTER_KITS.map((kit) => ({ ...kit, recipeIds: [...kit.recipeIds] }));
}
